[workspace]
members = [
    "nonogram-core",
    "nonogram-human-by-ai",
    "nonogram-propagation",
    "nonogram-graph-search",
    "nonogram-human",
    "nonogram-cli",
    "nonogram-convert",
    "nonogram-gui", "utils/katana-img-import",
]
resolver = "2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
